#ifndef KEYBOARD_PORT_H_
#define KEYBOARD_PORT_H_

#define LED_AC1_POSITION 1
#define LED_AC2_POSITION 2
#define LED_DC1_POSITION 3
#define LED_DC2_POSITION 4
#define LED_FLT_POSITION 5
#define LED__ON_POSITION 6

#endif

